services:
  - type: web
    name: telegram-payment-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: TRON_API_KEY
        sync: false
      - key: USDT_WALLET_ADDRESS
        sync: false
